name: Build and upload APK

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build and Upload to release
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Create .env File
        run: echo "APP_ID=${{ secrets.APP_ID }}" > .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'

      - name: verify flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: print .env file
        run: cat .env




        

