name: Flutter CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload to release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Create .env File
      run: echo "APP_ID=${{ secrets.APP_ID }}" > .env

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.6'
        channel: 'stable'

    - name: verify flutter version
      run: flutter --version

    - name: Install dependencies
      run: flutter pub get

    # - name: Load Environment Variables
    #   run: flutter pub run dotenv:generate

    - name: Build APK
      run: 
        # Access the API key from the secret
        flutter build apk

      #upload apk to artifacts with the name weather_app.apk with each iteration inceament the version code
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: weather_app.apk
        path: build/app/outputs/flutter-apk/app-release.apk

      #upload apk to github release and add paramenter token
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: weather_app.apk
        token: ${{ secrets.GIT_TOKEN }}
        tag: ${{ github.ref }}
        body: |
          Release ${{ github.ref }}
          - Build ${{ github.run_number }}
          - Commit ${{ github.sha }}
          - Branch ${{ github.ref }}
          - Author ${{ github.actor }}```
        name: ${{ github.ref }}
        prerelease: false
        draft: false

        

